services:
  web:
    image: ubongpr7/campaign_backend:latest
    env_file: .env 
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:7725"
    volumes:
      - .:/app
    ports:
      - "7725:7725"