# Generated by Django 5.1.5 on 2025-02-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_manager', '0002_ad_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('questions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_format',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('CAROUSEL', 'Carousel')], default='IMAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='ad',
            name='lead_form_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='pixel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='lead_form_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='pixel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DISAPPROVED', 'Disapproved')], default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='adset',
            name='bid_strategy',
            field=models.CharField(choices=[('LOWEST_COST', 'Lowest Cost'), ('COST_CAP', 'Cost Cap')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adset',
            name='budget_optimization',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adset',
            name='budget_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='bid_strategy',
            field=models.CharField(choices=[('LOWEST_COST', 'Lowest Cost'), ('COST_CAP', 'Cost Cap')], max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget_optimization',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='buying_type',
            field=models.CharField(choices=[('AUCTION', 'Auction'), ('RESERVED', 'Reserved')], max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='objective',
            field=models.CharField(choices=[('TRAFFIC', 'Traffic'), ('LEAD_GENERATION', 'Lead Generation'), ('CONVERSIONS', 'Conversions')], max_length=50),
        ),
    ]
