# Generated by Django 5.1.5 on 2025-02-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_manager', '0004_remove_ad_user_facebookadaccount_ad_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookadaccount',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='facebookadaccount',
            name='app_secret',
        ),
    ]
