# Generated by Django 5.1.5 on 2025-02-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_manager', '0005_remove_facebookadaccount_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookadaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
