# Generated by Django 5.1.5 on 2025-02-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_subscription_user_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pixel_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
