# Generated by Django 5.1.5 on 2025-01-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_api_key_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilephoto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
    ]
