# Generated by Django 5.1.5 on 2025-02-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_pay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price_per_vsl',
        ),
    ]
