# Generated by Django 5.1.5 on 2025-02-04 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_pay', '0002_remove_plan_price_per_vsl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe_pay.stripecustomer'),
        ),
    ]
